### ISSUE TITLE
Hi wts problem in on line 62 for example..?

### ISSUE THREAD

**Issue by EOM** [openswoole/dashboard#1]
**Not run... problem logs is ;-(**

openswoole    | Fatal error: Uncaught Error: Undefined constant "OPENSWOOLE_STATS_OPENMETRICS" in /var/www/server.php:62
openswoole    | Stack trace:
openswoole    | #0 {main}
openswoole    |   thrown in /var/www/server.php on line 62
openswoole    | [2021-12-26 05:11:09 *72.3]     ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Error: Undefined constant "OPENSWOOLE_STATS_OPENMETRICS" in /var/www/server.php:62
openswoole    | Stack trace:
openswoole    | #0 {main}
openswoole    |   thrown in /var/www/server.php on line 62
openswoole    | [2021-12-26 05:11:09 $17.0]     WARNING Server::check_worker_exit_status(): worker(pid=72, id=3) abnormal exit, status=255, signal=0

**Comment by doubaokun** [comment]
@EOM you have to update Docker image to be the latest version:

```
docker pull openswoole/swoole:latest
```
When you check the version, it should be >= 4.9.0:

```
docker run --rm openswoole/swoole:latest php --ri openswoole
```

**Comment by EOM** [comment]
Gracias

> @EOM tienes que actualizar la imagen de Docker para que sea la última versión:
> 
> ```
> **docker pull openswoole/swoole:latest**
> ```
> 
> Cuando verifique la versión, debería ser> = 4.9.0:
> 
> ```
> docker run --rm openswoole/swoole:latest php --ri openswoole
> ```

Gracias ;) 
Saludos de Argentina
